### ISSUE TITLE
Fresh install of extension does not have defaults set

### ISSUE THREAD

**Issue by ddoron** [ligyxy/KeyboardStartPage#1]
Hi, thanks for a very useful extension!!
Not a big deal personally, but I thought I'd mention that I installed this extension on a new user profile in Chrome on MacOS 10.11.6, and the options were not the default, I had to click "reset to defaults" to get the settings described in the README.

Attached is a screenshot of the settings after a fresh installation. Perhaps it's also worth noting: these aren't the options from my other profile on the same installation of Chrome, either.
<img width="451" src="https://user-images.githubusercontent.com/20175666/29217732-a1ef390c-7e80-11e7-9d97-81d06b75f2f0.png">

**Comment by gyli** [comment]
Thanks for reporting. I can reproduce this bug, that it's showing the wrong default options.

**Comment by gyli** [comment]
Fixed in 0.3.2
